services:
  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable port=5432"
    ports:
      - 8000:8000
    volumes:
      - /home/masoud/logs/:./logs
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data
  
volumes:
  pgdata: {}