CREATE TABLE "Customers" (
  "CustomerID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" VARCHAR,
  "LastName" VARCHAR,
  "PhoneNumber" VARCHAR,
  "Email" VARCHAR,
  "Address" TEXT
);


CREATE TABLE "Orders" (
  "OrderID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CustomerID" INT,
  "OrderDateTime" timestamp,
  "TotalPrice" bigint
);

CREATE TABLE "OrderItems" (
  "OrderItemID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderID" INT,
  "ItemID" INT,
  "Quantity" INT,
  "Subtotal" bigint
);

CREATE TABLE "Staff" (
  "StaffID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" VARCHAR,
  "LastName" VARCHAR,
  "Role" VARCHAR,
  "PhoneNumber" VARCHAR,
  "Email" VARCHAR
);

CREATE TABLE "Payment" (
  "PaymentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderID" INT,
  "PaymentDateTime" timestamp,
  "PaymentMethod" VARCHAR
);

ALTER TABLE "Orders" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customers" ("CustomerID");
ALTER TABLE "OrderItems" ADD FOREIGN KEY ("OrderID") REFERENCES "Orders" ("OrderID");
ALTER TABLE "Payment" ADD FOREIGN KEY ("OrderID") REFERENCES "Orders" ("OrderID");
