CREATE TABLE "Customers" (
  "CustomerID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" VARCHAR,
  "LastName" VARCHAR,
  "PhoneNumber" VARCHAR,
  "Email" VARCHAR,
  "Address" TEXT
);

CREATE TABLE "Tables" (
  "TableID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TableName" VARCHAR,
  "Capacity" INT
);

CREATE TABLE "Reservations" (
  "ReservationID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CustomerID" INT,
  "TableID" INT,
  "ReservationDateTime" DATETIME,
  "NumGuests" INT
);

CREATE TABLE "MenuItems" (
  "ItemID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ItemName" VARCHAR,
  "Description" TEXT,
  "Price" bigint
);

CREATE TABLE "Orders" (
  "OrderID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CustomerID" INT,
  "OrderDateTime" DATETIME,
  "TotalPrice" bigint
);

CREATE TABLE "OrderItems" (
  "OrderItemID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderID" INT,
  "ItemID" INT,
  "Quantity" INT,
  "Subtotal" bigint
);

CREATE TABLE "Staff" (
  "StaffID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" VARCHAR,
  "LastName" VARCHAR,
  "Role" VARCHAR,
  "PhoneNumber" VARCHAR,
  "Email" VARCHAR
);

CREATE TABLE "Payment" (
  "PaymentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderID" INT,
  "PaymentDateTime" DATETIME,
  "PaymentMethod" VARCHAR
);

ALTER TABLE "Reservations" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customers" ("CustomerID");

ALTER TABLE "Reservations" ADD FOREIGN KEY ("TableID") REFERENCES "Tables" ("TableID");

ALTER TABLE "Orders" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customers" ("CustomerID");

ALTER TABLE "OrderItems" ADD FOREIGN KEY ("OrderID") REFERENCES "Orders" ("OrderID");

ALTER TABLE "OrderItems" ADD FOREIGN KEY ("ItemID") REFERENCES "MenuItems" ("ItemID");

ALTER TABLE "Payment" ADD FOREIGN KEY ("OrderID") REFERENCES "Orders" ("OrderID");
